### ISSUE TITLE
refreshing状态下的布局怎么控制高度呢？

### ISSUE THREAD

**Issue by chenweide** [react-native-component/react-native-smart-pull-to-refresh-listview#12]
在refresh_none、refresh_idle、will_refresh这几个状态下header都能按照我写的布局显示，但是在refreshing状态下header设置固定高度后整个布局会自动往上靠，能看到的只有整个高度的一小部分

**Comment by naivehhr** [comment]
提供的GIF吧，目测布局问题~

**Comment by chenweide** [comment]
是的，refreshing状态准备放一张gif和文字，现在是整张gif能看到了 ， 但是整个header会覆盖在前几个item上面

**Comment by naivehhr** [comment]
解了么？还是有点抽象...QQ 1903283729

**Comment by chenweide** [comment]
非常感谢作者的解答 通过pullDownStayDistance这个属性是可以给refreshing状态下的header设置一个固定的高度的
