### ISSUE TITLE
Jumping when view is rendering 

### ISSUE THREAD

**Issue by jittu-tutu** [react-native-component/react-native-smart-pull-to-refresh-listview#17]
I have tried pull to refresh for scrollview and added content with in PullToRefreshListView. 

Whenever the view is rendering, the entire view content in PullToRefreshListView, moving few points from bottom to Top. It looks like jumping whenever we render the screen. How to remove this jumping whenever view is rendering?

**Comment by jittu-tutu** [comment]
we have used PullToRefreshListView  for scroll view. We also have embedded list view(child view) in scroll view/PullToRefreshListView. Pull is working until  we scroll the list view which is embedded in PullToRefreshListView. Once we start scrolling the child  list view, then touch/pull is not working for parent view. The parent view is not taking the touch control.Can you please check this issue?

**Comment by cyqresig** [comment]
Dear jittu-tutu,
I don't think this package will work now when you embedded list view(child view) in PullToRefreshListView(using listView mode).  
I'll check it out but I am not sure whether it can be fixed.
