### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by syanbo** [react-native-component/react-native-smart-pull-to-refresh-listview#2]
当嵌套在react-native-scrollable-tab-view里面的时候，下拉会出现和左右滑动冲突问题

**Comment by cyqresig** [comment]
这个是android的scrollView嵌套事件冲突的问题，源生的解决方案是需要外层的scrollView水平移动时需要自定义判断手势轨迹的角度。目前react-native-scrollable-tab-view中的代码并没有对这块做处理。之后会考虑自定义一个新的react-native-scrollable-tab-view， 并针对这个问题做处理。

**Comment by cyqresig** [comment]
该问题是由于自定义View：RCTSwipeRefreshLayout中遗漏了传递手势事件给子元素的逻辑。
已发布了更新版本修正了这个问题。

**Comment by syanbo** [comment]
@cyqresig 抱歉我刚刚测试发现还是存在这个问题，因为对安卓不是很熟悉，请问是需求设置其他的属性吗？
嵌套在react-native-scrollable-tab-view里面，下拉还是会和左右滑动冲突，导致下拉到一半不会复原。

**Comment by cyqresig** [comment]
确实有问题，现在更新了1.6.1版本，恢复正常了。另外在https://github.com/cyqresig/ReactNativeComponentDemos
中android版也加入了嵌套在react-native-scrollable-tab-view的示例

**Comment by jdpxiaoming** [comment]
多谢作者的工作，新年快乐！
