### ISSUE TITLE
[Android] a piece of data?

### ISSUE THREAD

**Issue by syanbo** [react-native-component/react-native-smart-pull-to-refresh-listview#3]
安卓环境下 autoLoadMore={true} 
如果只有一条数据的时候，这条数据具有点击事件，下拉的时候会直接触发点击事件。

**Comment by cyqresig** [comment]
您好，我这边加入了示例（点击事件通过使用TouchableHighlight），但无法重现您描述的只有一条数据，自动加载更多时的问题，该示例已加入到[ReactNativeComponentDemos](https://github.com/cyqresig/ReactNativeComponentDemos)下。
