### ISSUE TITLE
[iOS]dataSource中的数据只能增加，不能减少

### ISSUE THREAD

**Issue by Darwin-Ming** [react-native-component/react-native-smart-pull-to-refresh-listview#5]
![simulator screen shot 4 jan 2017 11 11 57 am](https://cloud.githubusercontent.com/assets/13765156/21630717/c1c5a072-d26e-11e6-9cbe-bc352838e2a3.png)
当datasource减少就成这样。

**Comment by naivehhr** [comment]
没遇到楼主问题，方便的画可以提供一些代码或一张GIF图😁

**Comment by Darwin-Ming** [comment]
由于需要datasource数组中的数据可能减少，减少到显示不足一屏的时候，footer就跟着上来了。

**Comment by Darwin-Ming** [comment]
_onLoadMore = () => {
           //console.log('outside _onLoadMore start...')

           this.setTimeout( () => {

               //console.log('outside _onLoadMore end...')

               let length = this.state.dataList.length
               let addNum = 10
               let addedDataList = []
               if(length >= 100) {
                   addNum = 3
               }
               for(let i = 0; i < addNum; i++) {
                   this.state.dataList.pop();
               }
               let newDataList = this.state.dataList
               this.dataList = newDataList
               this.setState({
                   dataList: newDataList,
                   dataSource: this._dataSource.cloneWithRows(newDataList),
               })

               let loadedAll
               if(length >= 100) {
                   loadedAll = true
                   this._pullToRefreshListView.endLoadMore(loadedAll)
               }
               else {
                   loadedAll = false
                   this._pullToRefreshListView.endLoadMore(loadedAll)
               }

           }, 3000)
       }

**Comment by Darwin-Ming** [comment]
sorry，我知道该怎么使用了
