### ISSUE TITLE
When listview scrolling,  can not click return(navigator.pop())

### ISSUE THREAD

**Issue by naivehhr** [react-native-component/react-native-smart-pull-to-refresh-listview#7]
![11](https://cloud.githubusercontent.com/assets/5243456/22181004/d60a365e-e0bc-11e6-8701-7413dfc245c0.gif)

**Comment by cyqresig** [comment]
Dear naivehhr,
I can't reproduce that 'When listview scrolling, can not click return(navigator.pop())'. You can try the full demo(https://github.com/cyqresig/ReactNativeComponentDemos).

**Comment by naivehhr** [comment]
找到问题了。嵌套在 react-native-scrollable-tab-view 中使用时会出现这个问题~单独使用则没问题。

**Comment by cyqresig** [comment]
您好，嵌套在 react-native-scrollable-tab-view 中真机试了一下，还是没能重现出您说的问题-_-!，您可以试下ReactNativeComponentDemos中的use-with-react-native-scrollable-tab-view示例

**Comment by naivehhr** [comment]
这就尴尬了...我直接使用ListView 组件也会出现这个问题....
![11](https://cloud.githubusercontent.com/assets/5243456/22282150/9496871c-e315-11e6-811b-bef6e26157f2.gif)
***
"react": "15.4.2",
"react-native": "0.40.0",
"react-native-scrollable-tab-view": "^0.7.1",
"react-native-smart-pull-to-refresh-listview": "^1.6.8"
[PullListDemo.zip](https://github.com/react-native-component/react-native-smart-pull-to-refresh-listview/files/728938/PullListDemo.zip)

**Comment by cyqresig** [comment]
你的demo我跑起来看了，问题在于react-native-scrollable-tab-view不是用来给你做tabbar用的，只适合在一个界面内使用，可以看一下[ReactNativeComponentDemos](https://github.com/cyqresig/ReactNativeComponentDemos)中的use-with-react-native-scrollable-tab-view示例，是没有问题的。另外，tabbar纯js版的可以使用[react-native-tab-navigator](https://github.com/exponent/react-native-tab-navigator)
你的示例调整[Demo.zip](https://github.com/cyqresig/ReactNativeComponentDemos/tree/master/temp/Demo.zip)

**Comment by naivehhr** [comment]
恩恩，谢谢！现在项目中用的是自己封装的一个tabbar组件，也没有这个问题。至于react-native-scrollable-tab-view 我认为它还是可以作为一个tabbar来用，但是存在这样一个问题而已，一己拙见😁。已经提了一个issue 给 react-native-scrollable-tab-view ~~~此外react-native-smart-pull-to-refresh-listview是个很棒的组件，给到我很多帮助，感谢呢！这个问题我就关闭了，如果找到解决方案我会补充上来。明天就除夕了，春节快乐！新年大吉！
